apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-red-data
  namespace: node-red
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/node-red"
