kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: node-red-claim
  namespace: node-red
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
