apiVersion: v1
kind: Service
metadata:
  name: home-assistant-public
spec:
  selector:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: home-assistant
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
  type: LoadBalancer
  loadBalancerIP: "${home_assistant_ip}"
