apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/ha"
