apiVersion: v1
kind: Service
metadata:
  name: legocity-server-public
spec:
  selector:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: legocity
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer