apiVersion: v1
kind: Service
metadata:
  name: legocity-server
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: legocity
spec:
  type: ClusterIP
  ports:
    - name: legocity
      port: 8080
      targetPort: legocity
  selector:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: legocity
