apiVersion: v1
kind: PersistentVolume
metadata:
  name: mqtt-pv-volume
  namespace: mqtt
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
