apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-claim
  namespace: mqtt
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
